### PR TITLE
Refactoring design

### PR DESCRIPTION
**Pull request by sdkitono**
screen shot 2018-07-21 at 4 57 37 pm

### CODE REVIEW

**Comment by evantaurusta** [comment]
dang bruh, pr so huge.. have you incorporated my latest pr and did work seamlessly?

**Comment by sdkitono** [comment]
Yeah bro haha but we can go through together. Its huge coz putting in that theme components stuff

**Comment by sdkitono** [comment]
I will break down the commit this week

**Review by evantaurusta — APPROVED** [review]
I already checkout your branch locally in my machine and the only changes that I have to make is to remove import for Caregroup.css from the Caregroup.js container

**Pull request merged**
